contentfarm_server:
    image: klakegg/hugo:0.101.0
    command: server --watch --baseUrl=https://contentfarm.jacobgoldman.dev --appendPort=false
    volumes:
      - "./site:/src"
    ports:
      - "1313:1313"

generate_article:
  image: jmgoldman/generate-article
  volumes:
      - "./site/content:/content:rw"
